"""
Setup script to create the 'patient_analyses' table in Supabase.
Run this once to initialize the database schema.
"""
import asyncio
import os
from supabase import create_client, Client
from dotenv import load_dotenv

load_dotenv(dotenv_path=".env")

SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_KEY")

if not SUPABASE_URL or not SUPABASE_KEY:
    print("Error: SUPABASE_URL and SUPABASE_KEY locally must be set in .env")
    exit(1)

supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY)

SQL_SCHEMA = """
create table if not exists public.patient_analyses (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  patient_id text not null,
  drug text not null,
  risk_label text,
  confidence_score float,
  severity text,
  primary_gene text,
  diplotype text,
  phenotype text,
  detected_variants jsonb,
  recommended_action text,
  dose_adjustment text,
  alternative_drugs jsonb,
  monitoring_required boolean,
  cpic_guideline_reference text,
  llm_summary text,
  llm_mechanism text,
  llm_variant_significance text,
  llm_dosing_rationale text,
  processing_time_ms integer
);
"""

def create_table():
    print("Creating 'patient_analyses' table...")
    # Supabase-py doesn't expose a raw SQL method easily on the client for DDL
    # But we can try using the .rpc() method if a function existed, OR 
    # since we likely don't have a 'run_sql' generic RPC, we might have to guide the user.
    #
    # HOSTED SUPABASE LIMITATION: 
    # The client libraries (JS/Python) are 'PostgREST' clients. They perform CRUD on existing tables.
    # They CANNOT execute arbitrary DDL (CREATE TABLE) unless you have a stored procedure (RPC) to do so.
    #
    # Since I cannot run SQL directly from the client without an RPC, I will inform the user.
    
    print("\n⚠️  IMPORTANT: Supabase Client Limitation ⚠️")
    print("The Supabase Python client cannot run 'CREATE TABLE' statements directly.")
    print("You MUST run the following SQL in your Supabase Dashboard > SQL Editor:\n")
    print(SQL_SCHEMA)

if __name__ == "__main__":
    create_table()
