-- Create patient_analyses table for storing pharmacogenomic analysis results
-- Run this in your Supabase SQL Editor

CREATE TABLE IF NOT EXISTS patient_analyses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id TEXT NOT NULL,
    drug TEXT NOT NULL,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    
    -- Risk assessment
    risk_label TEXT NOT NULL,
    confidence_score DECIMAL(3,2) NOT NULL CHECK (confidence_score >= 0.0 AND confidence_score <= 1.0),
    severity TEXT NOT NULL,
    
    -- Pharmacogenomic profile
    primary_gene TEXT NOT NULL,
    diplotype TEXT NOT NULL,
    phenotype TEXT NOT NULL,
    detected_variants JSONB DEFAULT '[]',
    
    -- Clinical recommendation
    recommended_action TEXT,
    dose_adjustment TEXT,
    alternative_drugs JSONB DEFAULT '[]',
    monitoring_required BOOLEAN DEFAULT FALSE,
    cpic_guideline_reference TEXT,
    
    -- LLM explanation
    llm_summary TEXT,
    llm_mechanism TEXT,
    llm_variant_significance TEXT,
    llm_dosing_rationale TEXT,
    
    -- Quality metrics
    processing_time_ms INTEGER DEFAULT 0,
    
    -- Metadata
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_patient_analyses_patient_id ON patient_analyses(patient_id);
CREATE INDEX IF NOT EXISTS idx_patient_analyses_drug ON patient_analyses(drug);
CREATE INDEX IF NOT EXISTS idx_patient_analyses_timestamp ON patient_analyses(timestamp);
CREATE INDEX IF NOT EXISTS idx_patient_analyses_risk_label ON patient_analyses(risk_label);

-- Enable Row Level Security (RLS)
ALTER TABLE patient_analyses ENABLE ROW LEVEL SECURITY;

-- Create policy for allowing inserts (anyone can insert data)
CREATE POLICY "Allow insert operations" ON patient_analyses
    FOR INSERT WITH CHECK (true);

-- Create policy for allowing reads (anyone can read data)
CREATE POLICY "Allow select operations" ON patient_analyses
    FOR SELECT USING (true);

-- Create policy for allowing updates based on patient_id
CREATE POLICY "Allow update operations" ON patient_analyses
    FOR UPDATE USING (true) WITH CHECK (true);

-- Additional: Allow all operations for testing
CREATE POLICY "Allow all operations" ON patient_analyses
    FOR ALL USING (true) WITH CHECK (true);

-- Function to automatically update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Trigger to automatically update updated_at
CREATE TRIGGER update_patient_analyses_updated_at
    BEFORE UPDATE ON patient_analyses
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Grant necessary permissions
GRANT ALL ON patient_analyses TO anon;
GRANT ALL ON patient_analyses TO authenticated;
